apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: two-tier-app-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: two-tier-app

  namespaceSelector:
    matchNames:
      - default

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
