name: CI - Build and push docker-image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Set up dockerbuildx
        uses: docker/setup-buildx-action@v4

      - name: Login in to dockerhub
        uses: docker/login-action@v4
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/two-tier-flask-devops-observability:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/two-tier-flask-devops-observability:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max      
